start('c2console', 'PCC2 Console');

section('Synopsis',
        paragraph_default_help(';'),
        paragraph_synopsis('<b>c2console</b> [<b>--config=</b><i>FILE</i>] [<b>-D</b><i>KEY</i><b>=</b><i>VALUE</i>] [<i>ENV</i>=<i>VALUE</i>] [<i>COMMAND</i>...]'));

section('Description',
        paragraph_text('<i>c2console</i> provides a command-line interface to the microservices of the PlanetsCentral suite.'),
        paragraph_text('If a <i>COMMAND</i> is given, <i>c2console</i> executes that command and exits.',
                       'Otherwise, it will read and execute commands from standard input.'));

section('Options',
        paragraph_default_help(';'),
        paragraph_default_server_config(';'),
        paragraph_default_log(';'),
        paragraph_default_proxy($sep),
        paragraph_detail('<i>ENV</i><b>=</b><i>VALUE</i>',
                         paragraph_text('Set environment variable for script;')),
        paragraph_detail('<i>COMMAND...</i>',
                         paragraph_text('Command to execute (including parameters).')));

section('Command Language',
        paragraph_text('A <b>command</b> consists of a number of <b>words</b> separated by spaces.',
                       'The first word is the command name, all subsequent words are parameters.',
                       'Example:'),
        paragraph_synopsis('    echo hello'),
        paragraph_text('If words contain special characters (including spaces), they can be quoted using single quotes, double quotes, or braces.',
                       'Single-quoted words end at the next single quote, and can contain no further special characters.',
                       'Double-quoted words allow quoting of special characters using a backslash.',
                       'Brace-quoted words end at the next closing brace, honoring quotes and nested braces.'),
        paragraph_synopsis('    echo "hello"',
                           "    echo 'hello'",
                           '    echo {hello {nested}}'),
        paragraph_text('Brace quoting is typically used to pass a command as parameter to another command, as in'),
        paragraph_synopsis('    if $c {',
                           '      command',
                           '    }'),
        paragraph_text('In double-quoted words, you can use <b>\0</b> (null), <b>\n</b> (newline), <b>\r</b> (carriage-return), <b>\t</b> (tab),',
                       '<b>\u</b><i>####</i> (Unicode hex-escape, produces UTF-8), and <b>\x</b><i>##</i> (hex-escape, produces single byte) escapes;',
                       'every other character after backslash produces itself (most notably, <b>\\</b> (backslash), <b>\$</b> (dollar) and <b>\"</b> (quote)).'),
        paragraph_text('In unquoted and double-quoted words, you can use <b>$</b><i>X</i> (one-character name)',
                       'or <b>${</b><i>XXX</i><b>}</b> to refer to script environment variables.',
                       'Unlike in a shell, variables are <i>not</i> further split into words.'),
        paragraph_text('If a word is preceded by a <b>&lt;</b> (less-than) sign, the file named by the word is read and its content used instead. Example:'),
        paragraph_synopsis('    echo &lt;file.txt'),
        paragraph_text('Commands can be arranged in a <b>pipeline</b> by separating them with a <b>|</b> pipe character.',
                       'This causes the result of the first command to be appended as additional parameters to the second command.',
                       'Idioms using this are:'),
        paragraph_synopsis('    # read value from redis and place in environment variable',
                           '    redis get somekey | setenv k',
                           '',
                           '    # retrieve a list and iterate through it',
                           '    talk forumlsthread 1 | foreach i {talk threadstat $i | echo}'),
        paragraph_text('Commands produce a result or a failure.',
                       'If the result is not null, it will be shown as output.'),
    );

section('Commands',
        paragraph_text('By default, the console is in <b>global context</b>.',
                       'Topic-specific commands are in additional contexts.',
                       'To execute a topic specific command, you can use <i>topic command...</i>,',
                       'or enter the topic context using <i>topic</i>, and entering the subsequent commands without <i>topic</i> prefix.',
                       'Global commands are always accepted.'),
        paragraph_synopsis('    # topic plus command',
                           '    talk forumlsthread 1',
                           '    talk forumlsthread 2',
                           '',
                           '    # topic, then commands',
                           '    talk',
                           '    forumlsthread 1',
                           '    forumlsthread 2'),
        paragraph_text('The <b>..</b> (dot-dot), <b>up</b> or <b>exit</b> command closes the active topic context.'));

subsect('Global Commands',
        paragraph_text('For details, see <link>pcc:index:group:globalconsolecommand</link>.'));

subsect('Server Connection Contexts',
        paragraph_text('Server connection contexts are',
                       '<b>doc</b>,',
                       '<b>download</b>,',
                       '<b>file</b>,',
                       '<b>format</b>,',
                       '<b>host</b>,',
                       '<b>hostfile</b>,',
                       '<b>mailout</b>,',
                       '<b>redis</b>,',
                       '<b>talk</b>,',
                       '<b>user</b>.'),
        paragraph_text('When the context is entered, a connection to the respective service is established.',
                       'All further commands are sent to the service, unless they match a built-in command.'),
        paragraph_detail('<b>repeat</b> <i>N</i> <i>COMMAND...</i>',
                         paragraph_text('For benchmarking: repeat the given command and discard the result.',
                                        'Print time taken;')),
        paragraph_detail('<b>reconnect</b>, <b>reset</b>',
                         paragraph_text('Disconnect and reconnect; discards server-side session state;')),
        paragraph_detail('<b>exec</b> <i>COMMAND...</i>',
                         paragraph_text('Send specified command to server.',
                                        'Use to send commands that have the same name as a built-in command.')));

subsect('Router Connection Context',
        paragraph_text('The <b>router</b> context talks to the <link>c2router-server(6)</link> service.',
                       'Commands are sent to the service as-is,',
                       'unless they match a built-in command.',
                       'As another exception, if a session has been selected and a command matches a session command,',
                       'it is submitted to that session (by prefixing it with an <b>S</b> line).'),
        paragraph_detail('<b>repeat</b> <i>N</i> <i>COMMAND...</i>',
                         paragraph_text('For benchmarking: repeat the given command and discard the result.',
                                        'Print time taken;')),
        paragraph_detail('<b>s</b> <i>N</i> <i>COMMAND...</i>',
                         paragraph_text('Submit the given command to a session;')),
        paragraph_detail('<b>s</b> <i>N</i>',
                         paragraph_text('Select session for future session commands.',
                                        'Session commands are <b>help</b>, <b>stat</b>, <b>get</b>, <b>post</b>, <b>quit</b>, and parameterless <b>save</b>.',
                                        'Note that there currently is no way to send a <b>post</b> payload.')));

subsect('Export Context',
        paragraph_text('The <b>export</b> context replaces the former <b>c2dbexport</b> utility.',
                       'Each of the commands will produce a script on standard output, that will recreate the exported situation in a way.'),
        paragraph_detail('<b>db</b> [<b>--delete</b>] <i>WILDCARD</i>...',
                         paragraph_text('Export database keys matching the given wildcards.',
                                        'The resulting script will add these keys to the target database instance.',
                                        'With <b>--delete</b>, the script will start with a command to delete all keys matching the given wildcards,',
                                        'allowing import into a nonempty database.')),
        paragraph_detail('<b>object</b> [<b>--</b><i>OPTION</i>] <i>TYPE</i><b>:</b><i>ID</i>...',
                         paragraph_text('Export objects from database, preserving links.',
                                        'The resulting script will add these objects to the target database instance.',
                                        'Links will be preserved, i.e. if the object is a user, their PMs will be exported,',
                                        'and the names of the users they were sent to.'),
                         paragraph_text('Option <b>--recursive</b> (default) requests the following objects with full details and related objects.',
                                        'Option <b>--full</b> requests the following objects with full details, but only base information for related objects.',
                                        'Option <b>--header</b> requests only the bare minimum object header ("this object exists").',
                                        'Output will be redacted to contain user-specific information only if the user is part of the export with at least full level.'),
                         paragraph_text('Option <b>--files=inline</b> (default) requests that files contained in the export job are represented as inline strings in the resulting script.',
                                        'Option <b>--files=normal</b> will create a directory <i>host</i> or <i>user</i>,',
                                        'and place files in it according to their location in the file service; the result script will read them from there.',
                                        'Option <b>--files=dedup</b> will create files under names corresponding to their content hash, storing each file copy only once.',
                                        'Especially for game exports, this will save a lot of disk space because backups are very repetetive,',
                                        'but will make it impossible to manually analyze the exported files using other tools.',
                                        'Option <b>--files=none</b> disables export of files.'),
                         paragraph_text('Supported object types are:',
                                        '<b>email</b> (email address),',
                                        '<b>file</b>/<b>userfile</b> (user file, <i>ID</i> is directory name),',
                                        '<b>forum</b> (forum, <i>ID</i> is numeric Id),',
                                        '<b>game</b> (game, <i>ID</i> is numeric Id),',
                                        '<b>group</b> (forum group, <i>ID</i> is group name),',
                                        '<b>host</b> (host version, <i>ID</i> is name),',
                                        '<b>hostfile</b> (host file, <i>ID</i> is directory name),',
                                        '<b>master</b> (master utility, <i>ID</i> is name),',
                                        '<b>msg</b>/<b>post</b> (forum post, <i>ID</i> is numeric Id),',
                                        '<b>pm</b> (private message, <i>ID</i> is numeric Id),',
                                        '<b>shiplist</b> (ship list, <i>ID</i> is name),',
                                        '<b>thread</b> (forum thread, <i>ID</i> is numeric Id),',
                                        '<b>token</b> (login token, <i>ID</i> is token value),',
                                        '<b>tool</b> (host utility, <i>ID</i> is name),',
                                        '<b>user</b> (user, <i>ID</i> is user Id).')));

section('Environment',
        paragraph_default_server_environment(';'),
        paragraph_default_environment());

section('Author',
        paragraph_default_author());

section('See Also',
        paragraph_link_list('pcc2(6)'));
